ARG GO_VERSION=1.26
FROM golang:${GO_VERSION} AS builder
# ARG GOPROXY=direct
ARG GOPROXY=https://proxy.golang.org
WORKDIR /go/src/github.com/mcmy/nps2
COPY . .
RUN go mod edit -go=$(go version | awk '{print $3}' | sed 's/go//') && \
    go mod tidy && \
    go get -d -v ./...
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" ./cmd/npc/npc.go

FROM alpine
RUN apk add --no-cache tzdata nano ca-certificates && update-ca-certificates
COPY --from=builder /go/src/github.com/mcmy/nps2/npc /
VOLUME /conf
ENTRYPOINT ["/npc"]
